name: Check

on:
  push:
    branches: [ trunk ]

env:
  ZIG_VERSION: 0.14.0-dev.1911+3bf89f55c

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install wayland-protocols libwayland-dev libxkbcommon-dev # Wayland
        sudo apt-get install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev # X11

    - name: Install DirectXShaderCompiler
      run: |
        curl https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2407/linux_dxc_2024_07_31.x86_64.tar.gz -L | tar -zx
        echo "$PWD/bin" >> $GITHUB_PATH

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{env.ZIG_VERSION}}

    - name: Type check
      run: zig build check

  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install DirectXShaderCompiler
      run: |
        Invoke-WebRequest -uri "https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2407/dxc_2024_07_31.zip" -Method "GET" -OutFile dxc.zip
        Expand-Archive dxc.zip
        Add-Content $env:GITHUB_PATH ";.\dxc\bin\x86"

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{env.ZIG_VERSION}}

    - name: Type check
      run: zig build check