name: CI

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list https://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
        sudo apt-get update
        sudo apt-get install wayland-protocols libwayland-dev libxkbcommon-dev # Wayland
        sudo apt-get install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev # X11
        sudo apt-get install vulkan-validationlayers mesa-vulkan-drivers # Vulkan

    - name: Install DirectXShaderCompiler
      run: |
        curl https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2407/linux_dxc_2024_07_31.x86_64.tar.gz -L | tar -zx
        echo "$PWD/bin" >> $GITHUB_PATH

    - name: Setup Zig
      uses: mlugg/setup-zig@v2

    # Workaround for https://codeberg.org/ziglang/zig/issues/31964
    - name: Create zig cache tmp dir
      run: |
        test "$(zig version)" = "0.16.0"
        mkdir -p "$(zig env | grep '\.global_cache_dir' | sed 's/.*= "\(.*\)".*/\1/')/tmp"

    - name: Type check
      run: zig build check

    - name: CPU tests
      run: zig build run-cpu-tests

    - name: GPU tests
      run: zig build run-gpu-tests

  windows:
    runs-on: windows-2025

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install DirectXShaderCompiler
      run: |
        Invoke-WebRequest -uri "https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2407/dxc_2024_07_31.zip" -Method "GET" -OutFile dxc.zip
        Expand-Archive dxc.zip
        Add-Content $env:GITHUB_PATH ";.\dxc\bin\x86"

    - name: Setup Zig
      uses: mlugg/setup-zig@v2

    # Workaround for https://codeberg.org/ziglang/zig/issues/31964
    - name: Create zig cache tmp dir
      run: |
        if ((zig version) -ne "0.16.0") { exit 1 }
        New-Item -ItemType Directory -Force -Path "$(((zig env | Select-String 'global_cache_dir') -split '"')[1])\tmp"

    - name: Type check
      run: zig build check

    - name: CPU tests
      run: zig build run-cpu-tests
